services:
  # FastAPI アプリケーション (AIモデル実行)
  api:
    build:
      context: .
      dockerfile: Dockerfile # ルートにあるAPIサーバー用のDockerfile
    restart: unless-stopped
    environment:
      - MODEL_NAME=/app/models/production.pth/
    volumes:
      - ./src:/app/src # ソースコードの変更を即時反映
      - ./static:/app/static # static コードの変更を即時反映
      - ./models:/app/models:ro # モデルをRead-Onlyでマウント
    expose:
      - "8000" # コンテナ間通信用
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # Nginx リバースプロキシ (キャッシュ機能付き)
  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    volumes:
      # SSL関連を削除し、HTTPキャッシュ用の設定をマウント
      - ./nginx/nginx_http_cache.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_cache_data:/var/cache/nginx # Nginxキャッシュの永続化用
    ports:
      - "8000:80" # ホストの8000番ポートをNginxの80番ポートに接続
    depends_on:
      - api

volumes:
  nginx_cache_data:
