services:
  # FastAPI アプリケーション (AIモデル実行)
  api:
    build:
      context: .
      dockerfile: Dockerfile # ルートにあるAPIサーバー用のDockerfile
    restart: unless-stopped
    environment:
      - MODEL_NAME=${MODEL_NAME}
    volumes:
      - ./src:/app/src # ソースコードの変更を即時反映
      - ./static:/app/static # static コードの変更を即時反映
      - ./models:/app/models:ro # モデルをRead-Onlyでマウント
    expose:
      - "8000" # コンテナ間通信用
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck/"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s # モデル読み込みなど起動に時間がかかるため、30秒の猶予期間を設ける
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # Nginx リバースプロキシ (キャッシュ機能付き)
  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    volumes:
      # SSL関連を削除し、HTTPキャッシュ用の設定をマウント
      - ./nginx/nginx_http_cache.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_cache_data:/var/cache/nginx # Nginxキャッシュの永続化用
    ports:
      - "8000:80" # ホストの8000番ポートをNginxの80番ポートに接続
    depends_on:
      api:
        condition: service_healthy # apiサービスがhealthy状態になるまで待機する

volumes:
  nginx_cache_data:
