stages:
  download_wjazzd_dataset:
    cmd: >-
      curl https://jazzomat.hfm-weimar.de/download/downloads/wjazzd.db
      -o data/raw/wjazzd.db
    outs:
      - data/raw/wjazzd.db

  make_dataset:
    cmd: >-
      uv run python -m src.make_dataset
      data/raw/wjazzd.db
      data/interim/train.json

