stages:
  download_wjazzd_dataset:
    cmd: >-
      curl https://jazzomat.hfm-weimar.de/download/downloads/wjazzd.db
      -o data/raw/wjazzd.db
    outs:
      - data/raw/wjazzd.db

  make_dataset:
    cmd: >-
      uv run python -m src.model.make_dataset
      data/raw/wjazzd.db
      data/interim/train.json
    deps:
      - src/model/make_dataset.py
      - data/raw/wjazzd.db
    outs:
      - data/interim/train.json

  train_model_llama-midi:
    cmd: >-
      uv run python -m src.model.train_model
      --model_name 'dx2102/llama-midi'
      --num_train_epochs ${train_epochs}
      data/interim/train.json
      models/llama-midi-e${train_epochs}.pth/
    deps:
      - src/model/train_model.py
      - data/interim/train.json
    outs:
      - models/llama-midi-e${train_epochs}.pth/

  train_model_llama_3.2-1b:
    cmd: >-
      uv run python -m src.model.train_model
      --model_name 'unsloth/Llama-3.2-1B-bnb-4bit'
      --num_train_epochs ${train_epochs}
      data/interim/train.json
      models/llama-3.2-1b-e${train_epochs}.pth/
    deps:
      - src/model/train_model.py
      - data/interim/train.json
    outs:
      - models/llama-3.2-1b-e${train_epochs}.pth/

  download_soundfont:
    cmd: >-
      wget -q
      https://github.com/mrbumpy409/GeneralUser-GS/raw/refs/heads/main/GeneralUser-GS.sf2
      -O data/raw/FluidR3_GM.sf2
    outs:
      - data/raw/FluidR3_GM.sf2

  evaluate_model:
    cmd: >-
      uv run python -m src.model.evaluate
      --model_paths models/llama-midi-e${train_epochs}.pth/ models/llama-3.2-1b-e${train_epochs}.pth/
      --soundfont_path data/raw/FluidR3_GM.sf2
      && date > data/interim/flag_evaluate_model.txt
    deps:
      - src/model/evaluate.py
      - src/model/utils.py
      - src/model/melody_processor.py
      - src/model/chord_name_parser.py
      - models/llama-3.2-1b-e${train_epochs}.pth/
      - models/llama-midi-e${train_epochs}.pth/
      - data/raw/FluidR3_GM.sf2
    outs:
      - data/interim/flag_evaluate_model.txt
