stages:
  download_wjazzd_dataset:
    cmd: >-
      curl https://jazzomat.hfm-weimar.de/download/downloads/wjazzd.db
      -o data/raw/wjazzd.db
    outs:
      - data/raw/wjazzd.db

  make_dataset:
    cmd: >-
      uv run python -m src.model.make_dataset
      data/raw/wjazzd.db
      data/interim/train.json
    deps:
      - src/model/make_dataset.py
      - data/raw/wjazzd.db
    outs:
      - data/interim/train.json

  train_model:
    foreach: ${train_params}
    do:
      cmd: >-
        uv run python -m src.model.train_model
        --model_name "${item.model_path}"
        --num_train_epochs ${item.epochs}
        data/interim/train.json
        models/${key}.pth/
      deps:
        - src/model/train_model.py
        - src/model/utils.py
        - src/model/melody_processor.py
        - src/model/chord_name_parser.py
        - data/interim/train.json
      outs:
        - models/${key}.pth/

  download_soundfont:
    cmd: >-
      wget -q
      https://github.com/mrbumpy409/GeneralUser-GS/raw/refs/heads/main/GeneralUser-GS.sf2
      -O data/raw/FluidR3_GM.sf2
    outs:
      - data/raw/FluidR3_GM.sf2

  evaluate_model:
    foreach: ${train_params}
    do:
      cmd: >-
        uv run python -m src.model.evaluate
        --model_paths models/${key}.pth/
        --soundfont_path data/raw/FluidR3_GM.sf2
        && date > data/interim/flag_evaluate_model-${key}.txt
      deps:
        - src/model/evaluate.py
        - src/model/utils.py
        - src/model/melody_processor.py
        - src/model/chord_name_parser.py
        - src/model/visualize.py
        - models/${key}.pth/
        - data/raw/FluidR3_GM.sf2
      outs:
        - data/interim/flag_evaluate_model-${key}.txt
